version: 2.1

commands:
  runwatch:
    description: Gets GTM data at site and pushes it to GH
    parameters:
      targets:
        type: string
      github_repo:
        type: string
      github_owner:
        type: string
      github_tracking_branch:
        type: string
    steps:
      - run:
          name: Run GTM Watch
          command: |
            TARGETS=<<parameters.targets>> \
            GITHUB_REPO=<<parameters.github_repo>> \
            GITHUB_OWNER=<<parameters.github_owner>> \
            GITHUB_TRACKING_BRANCH=<<parameters.github_tracking_branch>> \
            npm start

jobs:
  gtmWatch:
    docker:
      - image: cimg/node:15.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - runwatch:
          targets: 'https://www.keeps.com/'
          github_tracking_branch: master
          github_repo: platform
          github_owner: ThirtyMadison
      - runwatch:
          targets: 'https://www.keeps.com/'
          github_tracking_branch: master
          github_repo: keeps-frontend
          github_owner: ThirtyMadison

workflows:
  keeps:          
    jobs:
      - gtmWatch:
          context:
            - shared-build-context-1
      
